sudo: required
language: python
services:
  - docker
env:
  - TOXENV=py36
  - TOXENV=py37
  - TOXENV=flake8
  - TOXENV=pylint
  - TOXENV=mypy
before_install:
  - docker build --no-cache -t tox-python -f Dockerfile.tests .
script:
  - docker run --rm -t -v $PWD:/data -w /data -e USER_ID=$UID -e GROUP_ID=$UID tox-python tox -v -e $TOXENV
